version: '3.5'
services:
  web:
    container_name: orn_web
    build: .
    command: mix phx.server
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - .:/web:cached
    ports:
      - 4000:4000
      - 4001:4001
    links:
      - db
    depends_on:
      - db

  db:
    container_name: orn_db
    image: postgres:12
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/web:cached
      - orn_db:/var/lib/postgresql/data:cached

  redis:
    container_name: orn_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  orn_db: null
  redis-data: null
